#!/usr/bin/env bash
# This script will display information about subdomains.
display_host ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", varsub, $4, $5}' varsub=$subdomain
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ]; then
	display_host "$1" "$subdomain"
    fi
done
