#!/usr/bin/env bash
# Configures an NGINX server with a custom HTTP header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx start
